"""empty message

Revision ID: 88c7b526002d
Revises: None
Create Date: 2016-11-08 16:47:59.266071

"""

# revision identifiers, used by Alembic.
revision = '88c7b526002d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    ### end Alembic commands ###
